### ISSUE TITLE
Feature request: CIDR support for IP Bypass

### ISSUE THREAD

**Issue by ghost** [elie195/duo_provider#13]
Would it be possible to add CIDR notation support to the IP Bypass list, such that a subnet could be bypassed? For example, 192.168.0.0/24 would bypass all 255 addresses in the 192.168.0.x subnet.

**Comment by elie195** [comment]
Sure, working on it now. Hopefully should have it done this weekend.

**Comment by elie195** [comment]
Added support for networks (in CIDR notation) for IP Bypass as requested, with the help of @valenting ‘s fork. The most recent commit (app version 2.4.0) contains these changes. The app has also been updated in the ownCloud App Store and Marketplace, if you prefer using these channels.
