### ISSUE TITLE
Nginx backend not supported

### ISSUE THREAD

**Issue by elie195** [elie195/duo_provider#18]
Due to the use of the getallheaders() function(which is Apache-specific apparently), servers which use nginx are not supported. 

The following error is thrown:
:"GET","url":"\/apps\/files\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined function OCA\\\\Duo\\\\Provider\\\\getallheaders()\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/html\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/TwoFactorAuth\\\/Manager.php(129): OCA\\\\Duo\\\\Provider\\\\DuoProvider->isTwoFactorAuthEnabledForUser(Object(OC\\\\User\\\\User))\\n#1

**Comment by ciszard** [comment]
+1 I am also getting a similar error with NGINX. OwnCloud returns a internal server error when you install this plugin from the marketplace. 

`Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined function OCA\\\\Duo\\\\Provider\\\\getallheaders()\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/TwoFactorAuth\\\/Manager.php(129): OCA\\\\Duo\\\\Provider\\\\DuoProvider->isTwoFactorAuthEnabledForUser(Object(OC\\\\User\\\\User))\\n#1 [internal function]: OC\\\\Authentication\\\\TwoFactorAuth\\\\Manager->OC\\\\Authentication\\\\TwoFactorAuth\\\\{closure}(Object(OCA\\\\Duo\\\\Provider\\\\DuoProvider))\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/TwoFactorAuth\\\/Manager.php(130): array_filter(Array, Object(Closure))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Authentication\\\/TwoFactorAuth\\\/Manager.php(67): OC\\\\Authentication\\\\TwoFactorAuth\\\\Manager->getProviders(Object(OC\\\\User\\\\User))\\n#4 \\\/var\\\/www\\\/owncloud\\\/core\\\/Middleware\\\/TwoFactorMiddleware.php(93): OC\\\\Authentication\\\\TwoFactorAuth\\\\Manager->isTwoFactorAuthenticated(Object(OC\\\\User\\\\User))\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/MiddlewareDispatcher.php(93): OC\\\\Core\\\\Middleware\\\\TwoFactorMiddleware->beforeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(929): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#12 \\\/var\\\/www\\\/owncloud\\\/index.php(56): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/duo\\\/lib\\\/Provider\\\/DuoProvider.php\",\"Line\":109}"}`
