### ISSUE TITLE
Two-factor authentication override for logins from specific IPs

### ISSUE THREAD

**Issue by leonardomarino** [elie195/duo_provider#3]
Hi @elie195 I would like to know if is possible to implement a function that will override the two-factor authentication for specific IPs. Please see this https://github.com/tweakier/duo_auth/issues/3 from a round cube webmail plugin that enables Duo Security Two Factor Authentication.

**Comment by elie195** [comment]
Hi @leonardomarino, thanks for the feature request! I did some testing and it looks like it shouldn't be a problem to override Duo if you'd like for specific IPs. I'll work on getting that implemented.

In the meantime, you can configure these IP restrictions at the Duo level in the Admin panel (if you have the Enterprise version), but perhaps you'd like this feature implemented if you don't have the Enterprise version :smile: 

P.S. - I will probably initially only support the client IP as seen by the server, so any configurations utilizing load balancers and such (like when clients are identified by the X-Forwarded-For HTML header) won't work off the bat.

**Comment by leonardomarino** [comment]
Thanks @elie195 !!! yes you are right, I would like to configure IP restrictions directly instead of the Duo Admin panel. Again, thanks for the implementation.
